### ISSUE TITLE
Remove lodash dependency

### ISSUE THREAD

**Issue by ogiermaitre** [kiyui/vuex-listener#10]
It is more a question and a remark than a bug. But I see that lodash is included in my build, and I retrace its inclusion to your plugin (btw very cool plugin).

**describe the bug**
To my understanding of your code, lodash is not a depedency (only lodash-decorator is). But it adds a few hundreds kb to my build.

**expected behavior**
Remove lodash from dependencies.

**Comment by ogiermaitre** [comment]
I also suggest removing lodash-decorator, has it can be replaced by two boolean variables. I can do a pull request if you are interested, as I tried this solution here: https://github.com/ogiermaitre/vuex-listener/commit/95709fbe2e72040a41d6da5a00d297703514cbce.

**Comment by kiyui** [comment]
Hi, yeah that works :smile: Perhaps you could make a PR so I can review the changes and properly credit you~

My only suggestions is to split this declaration between type & assignment to the constructor. 
```typescript
private mutationsAreListened: boolean = false;
```

**Comment by ogiermaitre** [comment]
Nice, thanks for that.  #11 implements the modifications.
